### ISSUE TITLE
Location of js file unclear

### ISSUE THREAD

**Issue by Histoirerurale** [metagridch/modern-metagrid-widget#2]
Good morning,

We are very happy that a new version of Metagrid got developped and we are now trying to implement it. But we are unfortunately facing some difficulties. 

It seems that we can't locate the js file : ./dist/metagrid-widget.es.js

In the folder /dist, we only found .ts files.

We tried to add the example code in one of our html files and got the following error:
![Error](https://github.com/user-attachments/assets/61aea13a-17c0-41a9-90ce-37c5f589e8cd)

We would be very grateful if you could help us figure out where our mistake lies.

Kind regards,

Archives of Rural History

**Comment by Histoirerurale** [comment]
Good afternoon,

Thank you very much, we were indeed able to implement the new metagrid widget thanks to your answer. (but the files are not visible on the main page under "Code" yet)

Now we implemented it on one page where the person has links on metagrid (https://www.histoirerurale.ch/pers/personnes/Schenkel,_Conrad_(1834_1917)__DB3078.html) and it works well.

We also tested it on a page without links (https://www.histoirerurale.ch/pers/personnes/Affolter,_Elise_(1835_1905)__DB48.html) and there we can read the following error in the console.

![grafik](https://github.com/user-attachments/assets/314b858f-f9d6-429a-a6dd-da9d47c20745)

Unfortunately, we were not able to understand the reason why this error appears. Do you have an idea what we would need to correct?

Thank you very much for your much needed help.

Kind regards,

Archives of Rural History

**Comment by tobinski** [comment]
Thanx to @giodi for stepping in. The 404 for "Affolter Elise" is the expected behavior of this API. If there is no concordance the server returns a 404
